SPDATA_FILES = spectral_data/MKSpDATA/MKSpType5500.in \
  spectral_data/MKSpDATA/MKSpType7500.in \
  spectral_data/MKSpDATA/MKSpType9900.in \
  spectral_data/MKSpDATA/MKSpType6850.in \
  spectral_data/MKSpDATA/MKSpType4750.in \
  spectral_data/MKSpDATA/MKSpType5000.in \
  spectral_data/MKSpDATA/MKSpType1700.in \
  spectral_data/MKSpDATA/MKSpType3750.in \
  spectral_data/MKSpDATA/MKSpType6500.in \
  spectral_data/MKSpDATA/MKSpType2250.in \
  spectral_data/MKSpDATA/MKSpType5800.in \
  spectral_data/MKSpDATA/MKSpType2050.in \
  spectral_data/MKSpDATA/MKSpType6800.in \
  spectral_data/MKSpDATA/MKSpType7050.in \
  spectral_data/MKSpDATA/MKSpType5400.in \
  spectral_data/MKSpDATA/MKSpType5200.in \
  spectral_data/MKSpDATA/MKSpType4000.in \
  spectral_data/MKSpDATA/MKSpType3900.in \
  spectral_data/MKSpDATA/MKSpType1800.in \
  spectral_data/MKSpDATA/MKSpType3400.in \
  spectral_data/MKSpDATA/MKSpType7200.in \
  spectral_data/MKSpDATA/MKSpType2800.in \
  spectral_data/MKSpDATA/MKSpType1450.in \
  spectral_data/MKSpDATA/MKSpType9850.in \
  spectral_data/MKSpDATA/MKSpType3800.in \
  spectral_data/MKSpDATA/MKSpType5100.in \
  spectral_data/MKSpDATA/MKSpType6700.in \
  spectral_data/MKSpDATA/MKSpType3350.in \
  spectral_data/MKSpDATA/MKSpType6050.in \
  spectral_data/MKSpDATA/MKSpType5750.in \
  spectral_data/MKSpDATA/MKSpType1050.in \
  spectral_data/MKSpDATA/MKSpType6200.in \
  spectral_data/MKSpDATA/MKSpType8800.in \
  spectral_data/MKSpDATA/MKSpType8550.in \
  spectral_data/MKSpDATA/MKSpType8200.in \
  spectral_data/MKSpDATA/MKSpType1750.in \
  spectral_data/MKSpDATA/MKSpType8250.in \
  spectral_data/MKSpDATA/MKSpType4450.in \
  spectral_data/MKSpDATA/MKSpType6600.in \
  spectral_data/MKSpDATA/MKSpType9450.in \
  spectral_data/MKSpDATA/MKSpType6250.in \
  spectral_data/MKSpDATA/MKSpType5250.in \
  spectral_data/MKSpDATA/MKSpType3550.in \
  spectral_data/MKSpDATA/MKSpType6300.in \
  spectral_data/MKSpDATA/MKSpType6150.in \
  spectral_data/MKSpDATA/MKSpType4200.in \
  spectral_data/MKSpDATA/MKSpType7350.in \
  spectral_data/MKSpDATA/MKSpType1150.in \
  spectral_data/MKSpDATA/MKSpType7400.in \
  spectral_data/MKSpDATA/MKSpType8600.in \
  spectral_data/MKSpDATA/MKSpType8350.in \
  spectral_data/MKSpDATA/MKSpType3200.in \
  spectral_data/MKSpDATA/MKSpType5650.in \
  spectral_data/MKSpDATA/MKSpType1850.in \
  spectral_data/MKSpDATA/MKSpType5550.in \
  spectral_data/MKSpDATA/MKSpType9350.in \
  spectral_data/MKSpDATA/MKSpType5600.in \
  spectral_data/MKSpDATA/MKSpType2000.in \
  spectral_data/MKSpDATA/MKSpType5050.in \
  spectral_data/MKSpDATA/MKSpType1950.in \
  spectral_data/MKSpDATA/MKSpType4950.in \
  spectral_data/MKSpDATA/MKSpType1600.in \
  spectral_data/MKSpDATA/MKSpType9550.in \
  spectral_data/MKSpDATA/MKSpType3000.in \
  spectral_data/MKSpDATA/MKSpType2600.in \
  spectral_data/MKSpDATA/MKSpType2500.in \
  spectral_data/MKSpDATA/MKSpType8150.in \
  spectral_data/MKSpDATA/MKSpType9100.in \
  spectral_data/MKSpDATA/MKSpType6450.in \
  spectral_data/MKSpDATA/MKSpType3700.in \
  spectral_data/MKSpDATA/MKSpType2850.in \
  spectral_data/MKSpDATA/MKSpType8650.in \
  spectral_data/MKSpDATA/MKSpType7600.in \
  spectral_data/MKSpDATA/MKSpType3450.in \
  spectral_data/MKSpDATA/MKSpType8750.in \
  spectral_data/MKSpDATA/MKSpType8900.in \
  spectral_data/MKSpDATA/MKSpType7850.in \
  spectral_data/MKSpDATA/MKSpType6350.in \
  spectral_data/MKSpDATA/MKSpType6650.in \
  spectral_data/MKSpDATA/MKSpType7800.in \
  spectral_data/MKSpDATA/MKSpType7550.in \
  spectral_data/MKSpDATA/MKSpType2150.in \
  spectral_data/MKSpDATA/MKSpType2950.in \
  spectral_data/MKSpDATA/MKSpType3250.in \
  spectral_data/MKSpDATA/MKSpType5900.in \
  spectral_data/MKSpDATA/MKSpType6000.in \
  spectral_data/MKSpDATA/MKSpType2550.in \
  spectral_data/MKSpDATA/MKSpType9300.in \
  spectral_data/MKSpDATA/MKSpType5950.in \
  spectral_data/MKSpDATA/MKSpType9000.in \
  spectral_data/MKSpDATA/MKSpType1100.in \
  spectral_data/MKSpDATA/MKSpType1650.in \
  spectral_data/MKSpDATA/MKSpType1900.in \
  spectral_data/MKSpDATA/MKSpType9750.in \
  spectral_data/MKSpDATA/MKSpType9400.in \
  spectral_data/MKSpDATA/MKSpType1200.in \
  spectral_data/MKSpDATA/MKSpType8000.in \
  spectral_data/MKSpDATA/MKSpType8700.in \
  spectral_data/MKSpDATA/MKSpType7250.in \
  spectral_data/MKSpDATA/MKSpType7700.in \
  spectral_data/MKSpDATA/MKSpType9150.in \
  spectral_data/MKSpDATA/MKSpType4400.in \
  spectral_data/MKSpDATA/MKSpType6900.in \
  spectral_data/MKSpDATA/MKSpType4150.in \
  spectral_data/MKSpDATA/MKSpType2100.in \
  spectral_data/MKSpDATA/MKSpType4100.in \
  spectral_data/MKSpDATA/MKSpType4500.in \
  spectral_data/MKSpDATA/MKSpType4700.in \
  spectral_data/MKSpDATA/MKSpType4800.in \
  spectral_data/MKSpDATA/MKSpType3100.in \
  spectral_data/MKSpDATA/MKSpType7650.in \
  spectral_data/MKSpDATA/MKSpType5150.in \
  spectral_data/MKSpDATA/MKSpType1000.in \
  spectral_data/MKSpDATA/MKSpType9050.in \
  spectral_data/MKSpDATA/MKSpType6550.in \
  spectral_data/MKSpDATA/MKSpType4050.in \
  spectral_data/MKSpDATA/MKSpType8300.in \
  spectral_data/MKSpDATA/MKSpType3300.in \
  spectral_data/MKSpDATA/MKSpType7750.in \
  spectral_data/MKSpDATA/MKSpType8100.in \
  spectral_data/MKSpDATA/MKSpType9800.in \
  spectral_data/MKSpDATA/MKSpType4350.in \
  spectral_data/MKSpDATA/MKSpType3950.in \
  spectral_data/MKSpDATA/MKSpType5450.in \
  spectral_data/MKSpDATA/MKSpType2300.in \
  spectral_data/MKSpDATA/MKSpType4250.in \
  spectral_data/MKSpDATA/MKSpType4550.in \
  spectral_data/MKSpDATA/MKSpType9650.in \
  spectral_data/MKSpDATA/MKSpType1250.in \
  spectral_data/MKSpDATA/MKSpType7900.in \
  spectral_data/MKSpDATA/MKSpType7150.in \
  spectral_data/MKSpDATA/MKSpType2350.in \
  spectral_data/MKSpDATA/MKSpType4850.in \
  spectral_data/MKSpDATA/MKSpType9500.in \
  spectral_data/MKSpDATA/MKSpType4650.in \
  spectral_data/MKSpDATA/MKSpType4900.in \
  spectral_data/MKSpDATA/MKSpType2450.in \
  spectral_data/MKSpDATA/MKSpType1500.in \
  spectral_data/MKSpDATA/MKSpType6950.in \
  spectral_data/MKSpDATA/MKSpType5850.in \
  spectral_data/MKSpDATA/MKSpType7000.in \
  spectral_data/MKSpDATA/MKSpType9600.in \
  spectral_data/MKSpDATA/MKSpType9700.in \
  spectral_data/MKSpDATA/MKSpType2650.in \
  spectral_data/MKSpDATA/MKSpType7100.in \
  spectral_data/MKSpDATA/MKSpType9950.in \
  spectral_data/MKSpDATA/MKSpType2700.in \
  spectral_data/MKSpDATA/MKSpType8050.in \
  spectral_data/MKSpDATA/MKSpType1550.in \
  spectral_data/MKSpDATA/MKSpType3600.in \
  spectral_data/MKSpDATA/MKSpType8450.in \
  spectral_data/MKSpDATA/MKSpType1400.in \
  spectral_data/MKSpDATA/MKSpType9250.in \
  spectral_data/MKSpDATA/MKSpType6750.in \
  spectral_data/MKSpDATA/MKSpType900.in \
  spectral_data/MKSpDATA/MKSpType5300.in \
  spectral_data/MKSpDATA/MKSpType6400.in \
  spectral_data/MKSpDATA/MKSpType7450.in \
  spectral_data/MKSpDATA/MKSpType8500.in \
  spectral_data/MKSpDATA/MKSpType4600.in \
  spectral_data/MKSpDATA/MKSpType3650.in \
  spectral_data/MKSpDATA/MKSpType3150.in \
  spectral_data/MKSpDATA/MKSpType10000.in \
  spectral_data/MKSpDATA/MKSpType8400.in \
  spectral_data/MKSpDATA/MKSpType5350.in \
  spectral_data/MKSpDATA/MKSpType9200.in \
  spectral_data/MKSpDATA/MKSpType8950.in \
  spectral_data/MKSpDATA/MKSpType2200.in \
  spectral_data/MKSpDATA/MKSpType7950.in \
  spectral_data/MKSpDATA/MKSpType7300.in \
  spectral_data/MKSpDATA/MKSpType4300.in \
  spectral_data/MKSpDATA/MKSpType3500.in \
  spectral_data/MKSpDATA/MKSpType5700.in \
  spectral_data/MKSpDATA/MKSpType3850.in \
  spectral_data/MKSpDATA/MKSpType3050.in \
  spectral_data/MKSpDATA/MKSpType950.in \
  spectral_data/MKSpDATA/MKSpType1350.in \
  spectral_data/MKSpDATA/MKSpType2400.in \
  spectral_data/MKSpDATA/MKSpType8850.in \
  spectral_data/MKSpDATA/MKSpType2900.in \
  spectral_data/MKSpDATA/MKSpType2750.in \
  spectral_data/MKSpDATA/MKSpType6100.in \
  spectral_data/MKSpDATA/MKSpType1300.in
